import {
  ClipboardDocumentIcon,
  DocumentDuplicateIcon,
  ScissorsIcon,
  BoldIcon,
  ItalicIcon,
  FlagIcon,
  LinkIcon,
  ArrowPathIcon,
  FolderIcon,
  ChevronDoubleDownIcon,
  ChevronRightIcon,
  UserIcon,
  PlusIcon,
  ChartBarIcon,
  DocumentTextIcon,
  ExclamationTriangleIcon,
  Squares2X2Icon,
  PaintBrushIcon,
  PencilIcon,
  MagnifyingGlassPlusIcon,
  MagnifyingGlassMinusIcon,
  RectangleStackIcon,
  ClockIcon,
  ArrowUturnLeftIcon,
  ArrowUturnRightIcon,
  TrashIcon,
  PrinterIcon,
  DocumentArrowDownIcon,
  ChevronDownIcon,
  ArrowsPointingInIcon,
  ArrowsPointingOutIcon,
  DocumentArrowUpIcon,
  EyeIcon,
  Cog6ToothIcon,
  ChatBubbleLeftRightIcon,
  LinkIcon as LinkIconSolid,
  // Additional icons for comprehensive coverage
  CheckIcon,
  XMarkIcon,
  InformationCircleIcon,
  QuestionMarkCircleIcon,
  ExclamationCircleIcon,
  CalendarIcon,
  CalendarDaysIcon,
  ClockIcon as ClockIconSolid,
  MapPinIcon,
  BuildingOfficeIcon,
  UserGroupIcon,
  WrenchScrewdriverIcon,
  CogIcon,
  AdjustmentsHorizontalIcon,
  AdjustmentsVerticalIcon,
  ViewColumnsIcon,
  TableCellsIcon,
  ListBulletIcon,
  Bars3Icon,
  SquaresPlusIcon,
  DocumentPlusIcon,
  FolderPlusIcon,
  DocumentIcon,
  DocumentTextIcon as DocumentTextIconSolid,
  DocumentDuplicateIcon as DocumentDuplicateIconSolid,
  ArrowUpIcon,
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ChevronUpIcon,
  ChevronLeftIcon,
  ChevronRightIcon as ChevronRightIconSolid,
  ChevronDoubleUpIcon,
  ChevronDoubleLeftIcon,
  ChevronDoubleRightIcon,
  MinusIcon,
  PlusIcon as PlusIconSolid,
  XMarkIcon as XMarkIconSolid,
  CheckIcon as CheckIconSolid,
  StarIcon,
  HeartIcon,
  BookmarkIcon,
  BookmarkSquareIcon,
  HomeIcon,
  HomeModernIcon,
  BuildingLibraryIcon,
  AcademicCapIcon,
  BeakerIcon,
  CommandLineIcon,
  ComputerDesktopIcon,
  CpuChipIcon,
  CubeIcon,
  CubeTransparentIcon,
  CurrencyDollarIcon,
  CurrencyPoundIcon,
  CurrencyEuroIcon,
  CurrencyYenIcon,
  DevicePhoneMobileIcon,
  DeviceTabletIcon,
  EnvelopeIcon,
  EnvelopeOpenIcon,
  FireIcon,
  GlobeAltIcon,
  GlobeAmericasIcon,
  HashtagIcon,
  KeyIcon,
  LightBulbIcon,
  LockClosedIcon,
  LockOpenIcon,
  MagnifyingGlassIcon,
  MapIcon,
  MusicalNoteIcon,
  PaperAirplaneIcon,
  PhoneIcon,
  PhotoIcon,
  PlayIcon,
  PlayCircleIcon,
  PresentationChartBarIcon,
  PresentationChartLineIcon,
  PuzzlePieceIcon,
  QrCodeIcon,
  RadioIcon,
  RocketLaunchIcon,
  RssIcon,
  ScaleIcon,
  ShieldCheckIcon,
  ShieldExclamationIcon,
  SignalIcon,
  SparklesIcon,
  SpeakerWaveIcon,
  SpeakerXMarkIcon,
  Square2StackIcon,
  Square3Stack3DIcon,
  SwatchIcon,
  TagIcon,
  TicketIcon,
  VideoCameraIcon,
  WifiIcon,
  WindowIcon,
  WrenchIcon,
} from '@heroicons/react/24/outline';

// Comprehensive icon mapping for all ribbon actions
export const iconMap = {
  // Clipboard actions
  paste: ClipboardDocumentIcon,
  cut: ScissorsIcon,
  copy: DocumentDuplicateIcon,
  formatPainter: PaintBrushIcon,
  
  // History actions
  undo: ArrowUturnLeftIcon,
  redo: ArrowUturnRightIcon,
  history: ClockIcon,
  
  // Font formatting
  bold: BoldIcon,
  italic: ItalicIcon,
  underline: DocumentTextIcon,
  strikethrough: DocumentTextIcon,
  textColor: PaintBrushIcon,
  highlight: PaintBrushIcon,
  
  // Task actions
  task: DocumentTextIcon,
  milestone: FlagIcon,
  summary: ChartBarIcon,
  subtask: ChevronRightIcon,
  parent: ChevronLeftIcon,
  
  // Linking
  link: LinkIcon,
  unlink: LinkIconSolid,
  chain: LinkIcon,
  breakLink: XMarkIcon,
  
  // Progress presets
  progress0: CheckIcon,
  progress25: CheckIcon,
  progress50: CheckIcon,
  progress75: CheckIcon,
  progress100: CheckIcon,
  
  // Print and export
  print: PrinterIcon,
  export: DocumentArrowDownIcon,
  import: DocumentArrowUpIcon,
  save: DocumentIcon,
  open: FolderIcon,
  new: DocumentPlusIcon,
  documentArrowUp: DocumentArrowUpIcon,
  documentArrowDown: DocumentArrowDownIcon,
  
  // Baseline
  baseline: ClockIcon,
  baselineCreate: ClockIcon,
  baselineCompare: ChartBarIcon,
  baselineClear: TrashIcon,
  
  // Zoom
  zoomIn: MagnifyingGlassPlusIcon,
  zoomOut: MagnifyingGlassMinusIcon,
  zoomFit: ArrowsPointingInIcon,
  zoomActual: ArrowsPointingOutIcon,
  magnifyingGlassPlus: MagnifyingGlassPlusIcon,
  magnifyingGlassMinus: MagnifyingGlassMinusIcon,
  arrowsPointingOut: ArrowsPointingOutIcon,
  arrowsPointingIn: ArrowsPointingInIcon,
  
  // View
  view: EyeIcon,
  grid: Squares2X2Icon,
  list: ListBulletIcon,
  table: TableCellsIcon,
  columns: ViewColumnsIcon,
  squares2X2: Squares2X2Icon,
  
  // Schedule
  schedule: CalendarIcon,
  calendar: CalendarDaysIcon,
  timeline: ClockIcon,
  gantt: ChartBarIcon,
  clock: ClockIcon,
  
  // Resources
  resource: UserIcon,
  resources: UserGroupIcon,
  assign: UserIcon,
  unassign: XMarkIcon,
  user: UserIcon,
  
  // Project
  project: FolderIcon,
  projects: RectangleStackIcon,
  projectNew: FolderPlusIcon,
  projectOpen: FolderIcon,
  folder: FolderIcon,
  rectangleStack: RectangleStackIcon,
  
  // Tools
  tools: WrenchScrewdriverIcon,
  settings: Cog6ToothIcon,
  preferences: CogIcon,
  options: AdjustmentsHorizontalIcon,
  
  // Navigation
  expand: ChevronDoubleDownIcon,
  collapse: ChevronDoubleUpIcon,
  expandAll: ChevronDoubleDownIcon,
  collapseAll: ChevronDoubleUpIcon,
  
  // Actions
  add: PlusIcon,
  remove: MinusIcon,
  delete: TrashIcon,
  edit: PencilIcon,
  duplicate: DocumentDuplicateIcon,
  plus: PlusIcon,
  trash: TrashIcon,
  pencil: PencilIcon,
  scissors: ScissorsIcon,
  
  // Status
  active: CheckIcon,
  inactive: XMarkIcon,
  warning: ExclamationTriangleIcon,
  error: ExclamationCircleIcon,
  info: InformationCircleIcon,
  question: QuestionMarkCircleIcon,
  exclamationTriangle: ExclamationTriangleIcon,
  
  // Communication
  chat: ChatBubbleLeftRightIcon,
  message: EnvelopeIcon,
  notification: EnvelopeIcon,
  chatBubbleLeftRight: ChatBubbleLeftRightIcon,
  
  // Data
  data: ChartBarIcon,
  chart: PresentationChartBarIcon,
  analytics: PresentationChartLineIcon,
  report: DocumentTextIcon,
  chartBar: ChartBarIcon,
  documentText: DocumentTextIcon,
  
  // System
  system: CogIcon,
  computer: ComputerDesktopIcon,
  mobile: DevicePhoneMobileIcon,
  tablet: DeviceTabletIcon,
  
  // Common UI
  close: XMarkIcon,
  check: CheckIcon,
  star: StarIcon,
  heart: HeartIcon,
  bookmark: BookmarkIcon,
  home: HomeIcon,
  search: MagnifyingGlassIcon,
  filter: AdjustmentsVerticalIcon,
  sort: AdjustmentsVerticalIcon,
  paintBrush: PaintBrushIcon,
  
  // Additional utility icons
  refresh: ArrowPathIcon,
  sync: ArrowPathIcon,
  update: ArrowPathIcon,
  reload: ArrowPathIcon,
  reset: ArrowPathIcon,
  arrowPath: ArrowPathIcon,
  arrowsPointingIn: ArrowsPointingInIcon,
  
  // Directional
  up: ArrowUpIcon,
  down: ArrowDownIcon,
  left: ArrowLeftIcon,
  right: ArrowRightIcon,
  back: ArrowLeftIcon,
  forward: ArrowRightIcon,
  
  // Chevrons
  chevronUp: ChevronUpIcon,
  chevronDown: ChevronDownIcon,
  chevronLeft: ChevronLeftIcon,
  chevronRight: ChevronRightIconSolid,
  chevronDoubleUp: ChevronDoubleUpIcon,
  chevronDoubleDown: ChevronDoubleDownIcon,
  chevronDoubleLeft: ChevronDoubleLeftIcon,
  chevronDoubleRight: ChevronDoubleRightIcon,
  
  // Specialized
  lock: LockClosedIcon,
  unlock: LockOpenIcon,
  key: KeyIcon,
  shield: ShieldCheckIcon,
  security: ShieldExclamationIcon,
  globe: GlobeAltIcon,
  world: GlobeAmericasIcon,
  location: MapPinIcon,
  building: BuildingOfficeIcon,
  library: BuildingLibraryIcon,
  school: AcademicCapIcon,
  science: BeakerIcon,
  code: CommandLineIcon,
  chip: CpuChipIcon,
  cube: CubeIcon,
  cubeTransparent: CubeTransparentIcon,
  money: CurrencyDollarIcon,
  pound: CurrencyPoundIcon,
  euro: CurrencyEuroIcon,
  yen: CurrencyYenIcon,
  phone: PhoneIcon,
  email: EnvelopeIcon,
  fire: FireIcon,
  hashtag: HashtagIcon,
  lightbulb: LightBulbIcon,
  music: MusicalNoteIcon,
  send: PaperAirplaneIcon,
  photo: PhotoIcon,
  play: PlayIcon,
  playCircle: PlayCircleIcon,
  puzzle: PuzzlePieceIcon,
  qr: QrCodeIcon,
  radio: RadioIcon,
  rocket: RocketLaunchIcon,
  rss: RssIcon,
  scale: ScaleIcon,
  signal: SignalIcon,
  sparkles: SparklesIcon,
  speaker: SpeakerWaveIcon,
  speakerMute: SpeakerXMarkIcon,
  stack: Square2StackIcon,
  stack3d: Square3Stack3DIcon,
  swatch: SwatchIcon,
  tag: TagIcon,
  ticket: TicketIcon,
  video: VideoCameraIcon,
  wifi: WifiIcon,
  window: WindowIcon,
  wrench: WrenchIcon,
} as const;

// Type for icon names
export type IconName = keyof typeof iconMap;
