export const buildQueue = {
  planned: [
    'Prompt 001 – Clipboard Tools',
    'Prompt 002 – Task Properties Drawer',
    'Prompt 003 – Task Linking',
    'Prompt 004 – Critical Path Analysis',
    'Prompt 005 – Resource Allocation',
    'Prompt 006 – Baseline Management',
    'Prompt 007 – Progress Tracking',
    'Prompt 008 – Cost Management',
    'Prompt 009 – Risk Management',
    'Prompt 010 – Reporting Tools',
    'Prompt 011 – Import/Export Functionality',
    'Prompt 012 – User Preferences',
    'Prompt 013 – Advanced Filtering',
    'Prompt 014 – Custom Views',
    'Prompt 015 – Collaboration Features',
    'Prompt 016 – Notification System',
    'Prompt 017 – Audit Trail',
    'Prompt 018 – Backup & Recovery',
    'Prompt 019 – Performance Optimization',
    'Prompt 020 – Accessibility Features',
    'Prompt 021 – Mobile Responsiveness',
    'Prompt 022 – Offline Mode',
    'Prompt 023 – Data Validation',
    'Prompt 024 – Workflow Automation',
    'Prompt 025 – Integration APIs',
    'Prompt 026 – Advanced Scheduling',
    'Prompt 027 – Multi-Project Management',
    'Prompt 028 – Template System',
    'Prompt 029 – Advanced Analytics',
    'Prompt 030 – Custom Fields',
    'Prompt 031 – Time Tracking',
    'Prompt 032 – Document Management',
    'Prompt 033 – Issue Tracking',
    'Prompt 034 – Change Management',
    'Prompt 035 – Quality Assurance',
    'Prompt 036 – Safety Management',
    'Prompt 037 – Environmental Compliance',
    'Prompt 038 – Stakeholder Management',
    'Prompt 039 – Communication Tools',
    'Prompt 040 – Meeting Management',
    'Prompt 041 – Decision Tracking',
    'Prompt 042 – Lessons Learned',
    'Prompt 043 – Knowledge Base',
    'Prompt 044 – Training Management',
    'Prompt 045 – Certification Tracking',
    'Prompt 046 – Equipment Management',
    'Prompt 047 – Material Management',
    'Prompt 048 – Subcontractor Management',
    'Prompt 049 – Contract Management',
    'Prompt 050 – Financial Management',
    'Prompt 051 – Budget Tracking',
    'Prompt 052 – Cash Flow Management',
    'Prompt 053 – Earned Value Management',
    'Prompt 054 – Forecasting Tools',
    'Prompt 055 – Scenario Planning',
    'Prompt 056 – Monte Carlo Analysis',
    'Prompt 057 – Sensitivity Analysis',
    'Prompt 058 – Optimization Algorithms',
    // Add all pending prompt items here
  ],
  inProgress: [
    'Prompt 066 – Enhanced Task Management',
    'Prompt 067 – Advanced Gantt Features',
    'Prompt 068 – Performance Monitoring',
  ],
  completed: [
    'Prompt 001 – Home Ribbon Layout (Exact Asta Replica)',
    'Prompt 002 – Task Properties Drawer',
    'Prompt 003 – Task Linking',
    'Prompt 059 – Zoom In/Out & Fit to View Toolbar Group',
    'Prompt 060 – Drag & Drop Reordering in SidebarTree',
    'Prompt 061 – Task Grouping and Organization',
    'Prompt 062 – Add Milestone Marker Tool',
    'Prompt 063 – Add Undo / Redo Toolbar Group',
    'Prompt 064 – Add Colour Code Task Rows by Status',
    'Prompt 065 – Add Inline Task Editing in Grid',
    'Prompt 069 – Expand All and Collapse All Buttons',
    'Prompt 070 – Insert Task Below and Insert Summary Task',
    'Prompt 071 – Delete Task functionality',
    'Prompt 075 – Resource Calendar & Availability',
    'Prompt 076 – Custom Fields & Metadata',
    'Prompt 077 – Advanced Filtering & Search',
    'Prompt 078 – Go to Today Button',
    'Prompt 079 – Show Weekends Toggle',
    'Prompt 080 – Show Gridlines Toggle',
    'Prompt 081 – Show Critical Path Toggle',
    'Prompt 082 – Show Slack Toggle',
    'Prompt 083 – Zoom to Fit Button',
    'Prompt 085 – Today Button',
  ],
};
