name: Mirror Entire Repo

on:
  push: {}

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Guard against secret leakage
        run: |
          chmod +x tools/mirror/secret-guard.sh || true
          ./tools/mirror/secret-guard.sh || true

      - name: Setup SSH for mirror
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.MIRROR_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          printf "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

      - name: Prepare mirror working dir
        run: |
          rm -rf mirror && mkdir mirror
          cd mirror
          git init
          git remote add origin "${{ secrets.MIRROR_REPO_SSH }}"
          git checkout -b main || true

      - name: Copy repository (exclude heavy/build/secret files)
        run: |
          rsync -a --delete \
            --exclude '.git' \
            --exclude 'node_modules' \
            --exclude '.turbo' \
            --exclude '.next' \
            --exclude 'dist' \
            --exclude 'build' \
            --exclude 'coverage' \
            --exclude '.DS_Store' \
            --exclude '*.log' \
            --exclude '.env' \
            --exclude '.env.*' \
            ./ mirror/

      - name: Create mirror manifest
        run: |
          node -e "const fs=require('fs');const p={repo:process.env.GITHUB_REPOSITORY,sha:process.env.GITHUB_SHA,branch:process.env.GITHUB_REF_NAME,ts:new Date().toISOString()};fs.writeFileSync('mirror/mirror-manifest.json',JSON.stringify(p,null,2));"

      - name: Commit & push to mirror
        run: |
          cd mirror
          git add -A
          git -c user.name='Mirror Bot' -c user.email='mirror-bot@users.noreply.github.com' \
            commit -m "Mirror ${GITHUB_SHA} (${GITHUB_REF_NAME})" || true
          git push -f origin main
